language: python
services:
  - postgresql
python:
  - "2.7"
env:
  global:
  - TRAVIS_BUILD=true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database bucketlist;' -U postgres
  - cd bucketlist && python manage.py migrate
# command to run tests
script:
  - python manage.py test
  - coverage run --omit='*virtualenv*' manage.py test
after_success: coveralls
