language: python
python:
  - "2.7"
env:
  global:
  - TRAVIS_BUILD=true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - cd bucketlist
  - ./manage.py test
  - coverage run --omit='*virtualenv*' manage.py test
after_success: coveralls
